dbaas/logical/migrations/0023_auto__del_field_database_contacts.py
dbaas/logical/models.py

- Delete field from model;
- Migration archive created;

Delete contacts field from database model

---

dbaas/workflow/steps/mysql/deploy/check_pupet.py

- Get code status on log file /var/log/ks-post.log in VM
- Raise an exception if code status is an error

Log and return puppet-setup result status

---

dbaas/workflow/steps/mysql/flipperfox_migration/check_pupet.py

- Logging last five lines of puppet-setup log file
- Getting and testing code status from puppet-setup
- Raising exception to undo the steps if returned code is an error

Log and return code status of puppet-setup on flipper to fox migration

---

dbaas/notification/tasks.py
dbaas/util/providers.py
dbaas/workflow/steps/util/resize/resize_vm.py
dbaas/workflow/steps/util/resize/start_vm.py
dbaas/workflow/steps/util/resize/stop_vm.py
dbaas/workflow/workflow.py

- Create start_workflow_ha and stop_workflow_ha methods for HA databases;
- Workflow deals with the instances instead of resize_database method;
- Change LOG messages for better comprehension.

Fix resize log enumeration

---

dbaas/workflow/steps/util/resize/__init__.py
dbaas/workflow/steps/util/resize/start_vm.py
dbaas/workflow/steps/util/resize/stop_vm.py

- Shows exception traceback on StartVM and StopVM;
- Solved name conflict between modules and methods (stop_vm, start_vm).

Fix a database resizing bug while doing rollback

---

dbaas/account/models.py
dbaas/account/tests/factory.py
dbaas/account/tests/test_account.py
dbaas/account/tests/test_team.py
dbaas/notification/admin/task_history.py

- Create a classmethod on Team to return all users from same team of a given user;
- Create tests for the method above;
- Filtering by team users instead of the current user on queryset (notification/admin/task_history.py);
- Create a new factory to create an User object instead of an AccountUser;

Users without admin privileges can see tasks from its team

---

dbaas/logical/static/js/database_admin.js

Improve add database form

---

dbaas/drivers/base.py
dbaas/drivers/replication_topologies/base.py
dbaas/drivers/replication_topologies/redis.py
dbaas/drivers/tests/test_replication_topologies/__init__.py
dbaas/drivers/tests/test_replication_topologies/test_redis.py
dbaas/logical/admin/database.py
dbaas/maintenance/tests/factory.py
dbaas/notification/management/arguments/factory.py
dbaas/notification/models.py
dbaas/notification/tasks.py
dbaas/notification/tests/factory.py
dbaas/notification/tests/test_arguments.py
dbaas/notification/util.py
dbaas/tsuru/views.py
dbaas/workflow/steps/util/database.py
dbaas/workflow/steps/util/infra.py
dbaas/workflow/steps/util/pack.py
dbaas/workflow/steps/util/resize/agents.py

- Refactored some steps code;
- Create an Arguments Factory;
- Create a generic test for all classes in factory;
- Implement arguments treatment on new pattern workflow methods.

Refactor args

---

dbaas/admin/templates/admin/confirmation_modal.html
dbaas/admin/templates/admin/submit_line.html
dbaas/dashboard/templates/dashboard/dashboard.html
dbaas/dbaas/templatetags/dbaas_tags.py
dbaas/logical/templates/logical/database/database_add_form.html
dbaas/logical/templates/logical/database/details/backup_tab.html
dbaas/logical/templates/logical/database/details/credentials_tab.html
dbaas/logical/templates/logical/database/details/destroy_tab.html
dbaas/logical/templates/logical/database/details/hosts_tab.html
dbaas/logical/templates/logical/database/details/parameters_tab.html
dbaas/logical/templates/logical/database/details/resizes_tab.html
dbaas/physical/admin/databaseinfra.py
dbaas/physical/admin/plan.py
dbaas/physical/admin/replication_topology.py
dbaas/physical/forms/replication_topology.py
dbaas/physical/templates/admin/physical/plan/change_form.html
dbaas/physical/templates/admin/physical/replicationtopology/change_form.html

Core modal

---

dbaas/admin/templates/admin/base_site.html
dbaas/system/templatetags/system_config.py

If you set configuration docs_url on system configuration the Docs
menu will appear on main menu.

Create Doc on main menu.

---

Dockerfile

Refactoring Dockerfile with [best practices](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/).
Changes:
* added all `apt` comands to same `RUN` layer;
* added command to clear list caches (` rm -rf /var/lib/apt/lists/*`);
* added `--no-install-recommends` option to `apt-get install`;
* added all `pip` commands to same `RUN` layer;
* change `easy_install` to `pip`;
* change `pip install -U pip` to `pip install --upgrade pip`

Refactoring Dockerfile with best practices

---

dbaas/logical/admin/database.py
dbaas/logical/views.py

-  New view added database_upgrade_patch_retry
-  Url added do admin

Bugfix - Upgrade Patch Retry not working from maintenance

---

dbaas/workflow/steps/util/vm.py

We do that because sometimes the failover command lock and we need
kill that and run manually. When we did that occurs 2 failovers.
To avoid that we add verification inside the loop

Verify is is_slave inside loop.

---

dbaas/djcelery_dbaas/admin.py

-  Executing save on each object instead of update as signals are not called.

Bugfix - Enable and Disable Tasks

---

dbaas/workflow/steps/util/k8s.py
dbaas/workflow/steps/util/volume_provider.py

The volume provider is generating this name

Remove dbaas logic to generate volume name

---

README.md

Fixes #571 
changes:
- **informations** -> **information**
- **avliable** -> **available**

typo fixes - update README.md

---

dbaas/logical/admin/database.py
dbaas/logical/templates/logical/database/details/base.html
dbaas/logical/templates/logical/database/details/historic_tab.html
dbaas/logical/templates/logical/database/details/history_tab.html
dbaas/logical/views.py

Database historic

---

dbaas/account/templates/account/profile.html
dbaas/admin/templates/admin/change_list_results.html
dbaas/admin/templates/admin/index.html
dbaas/dashboard/templates/dashboard/dashboard.html
dbaas/dashboard/templates/search/search.html
dbaas/dbaas/templates/adminplus/index.html
dbaas/logical/templates/logical/database/details/credentials_tab.html
dbaas/logical/templates/logical/database/details/dns_tab.html
dbaas/logical/templates/logical/database/details/history_tab.html
dbaas/logical/templates/logical/database/details/hosts_tab.html
dbaas/logical/templates/logical/database/details/migrate_tab.html
dbaas/logical/templates/logical/database/details/parameters_tab.html
dbaas/logical/templates/logical/database/task_schedule/scheduled_table.html

add a native class from bootstrap no enable table hover in a row.

add table-hover bootstrap class to tables

---

doc/Home.md
doc/dockerconfs.md
doc/drivers.md
doc/quickstart.md

Documentation Updated

---

.gitignore
dbaas/logical/views.py
dbaas/physical/admin/__init__.py
dbaas/physical/admin/core_replication_topology.py
dbaas/physical/admin/offering.py
dbaas/physical/admin/script.py

Inclusçao filtros em:
- Offerings: Number of CPUs, Memory e environments
- Core replication topologies: Engine e Engine Type
- Scripts: Replication Topology, Engine e Engine Type
Tela de databases, tab resizes: Ordenar as ofertas de disco pelo tamanho

inclusao de filtros e ordenacao da lista de ofertas de disco

---

dbaas/notification/tasks_disk_resize.py

Zabbix alternative ii

---

dbaas/notification/tasks_disk_resize.py

- Use host_mount_data_percentage for perform direct access in the VM to gathering
disk usage information
- Use the host property is_ol6 in host_mount_data_percentage to find what Linux
distribution is in use on VM

Adjust in tasks_disk_resize

---

dbaas/backup/tasks.py

Paralel backup

---

dbaas/maintenance/admin/database_migrate.py

Fixing error 500 in filtering values in list of database migrates

Fixing error 500 in filtering values in list of database migrates

---

requirements.txt

Update lib dbaas-aclapi to fix error to get token in backstage.

updating dbaas-aclapi

---

requirements.txt

update version of acl api

---

dbaas/logical/models.py
dbaas/logical/templates/logical/database/details/details_tab.html

Add new url in database details tab to show created changes to that database.

Add new url to show changes in chg_register api

---

dbaas/logical/templates/logical/database/details/cost_tab.html

Added loading div and reload button in costs tab.

Loading div and reload button in costs tab

---

dbaas/logical/views.py

Todas as Configurations foram adicionadas (dev e prod)
Todos os parametros de Credentials do Grafana foram adicionados (dev e prod)

change grafana dashboard url by environment type

---

dbaas/notification/admin/task_history.py

Added a new column in task history to show the database name

Feature: Added a new column, column database name, in job history

---

dbaas/logical/templates/logical/database/details/migrate_tab.html
dbaas/logical/views.py

If there is a task in 'waiting', all buttons are disabled. For this, a variable was added in the back-end, that stores the state and sends it to the front-end. At the front-end it was necessary to add a new tag and checks in javascript to enable or disable the buttons.

Feature: Disable all buttons when there is database task on hold

---

dbaas/logical/templates/logical/database/details/details_tab.html
dbaas/logical/views.py
dbaas/maintenance/admin/database_stop_database_vm.py
dbaas/maintenance/task_stop_database_vm.py

fixing error in function start/stop in redis clusters databases.
add retry button in details tab when task in error.
fixing performance error in details tab.
removing update status database before creating tasks of start/stop.
removing unnecessary prints.

fixing start stop error in redis cluster

---

dbaas/maintenance/admin/database_migrate.py

Error on current step in rollback

Fix: Error on current step in rollback

---

dbaas/dbaas/middleware.py
dbaas/dbaas/settings.py
dbaas/dbaas/templates/deploy/deploy.html
dbaas/dbaas/urls.py
dbaas/dbaas/views.py

https://user-images.githubusercontent.com/36168066/214053264-097ba0a4-3f51-4951-86d5-fe6564ab2344.mp4

Redirect user when deploying

---

dbaas/logical/templates/logical/database/details/metrics_tab.html
dbaas/logical/views.py

Unificar Grafana Prometheus

---

dbaas/logical/templates/logical/database/details/migrate_tab.html
dbaas/logical/views.py

Added docstring documentation. Variable name change for better understanding and logic simplification.

Added docstring documentation and other simple changes

---

dbaas/backup/tasks.py
dbaas/workflow/steps/util/volume_provider.py

Exception in take snapshot

---

dbaas/workflow/steps/util/volume_provider.py

Changed url to fix upgrade disk. Same change is made in volume provider

Change url to fix upgrade disk

---

dbaas/workflow/steps/util/volume_provider.py

Fixed the function checks status of snapshot in recreate slave

Fix recreate slave

---

dbaas/drivers/base.py
dbaas/drivers/mysqldb.py
dbaas/drivers/replication_topologies/mysql.py
dbaas/logical/templates/logical/database/details/parameters_tab.html
dbaas/logical/views.py
dbaas/maintenance/models.py
dbaas/maintenance/task_configure_db_params.py
dbaas/workflow/steps/util/database.py

Precisa de uma Configuration ->
`max_connections_steps` = `0:1000,32768:2000,65536:4000,131072:6000`

Autoconfig max_connections MySQL

---

dbaas/logical/templates/logical/database/details/parameters_tab.html

AutoConfig - Legenda botao de AutoConfigure

---

dbaas/drivers/replication_topologies/base.py
dbaas/drivers/replication_topologies/mongodb.py
dbaas/drivers/replication_topologies/mysql.py
dbaas/drivers/replication_topologies/redis.py

- CreateDatabase
- AutoUpgradeVM
- Resize de VM
- RecreateSlave
- AddReadOnlyInstance
- ReinstallVM

Autoconfig - AutoConfig on DB Actions
